"""add_name_to_items_table

Revision ID: 58fcf9ab912e
Revises: b80f80d6240b
Create Date: 2024-09-30 17:31:23.541918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58fcf9ab912e"
down_revision: Union[str, None] = "b80f80d6240b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "name")
    # ### end Alembic commands ###
