"""init

Revision ID: 855e11c779be
Revises: 
Create Date: 2024-09-30 15:11:45.037262

"""

from typing import (
    Sequence,
    Union,
)

from alembic import (
    op,
)
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "855e11c779be"
down_revision: Union[
    str,
    None,
] = None
branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None
depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "phone",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "email",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "password",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "USER",
                "OWNER",
                name="role",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_users_phone"),
        "users",
        ["phone"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_users_phone"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_email"),
        table_name="users",
    )
    op.drop_table("users")
    # ### end Alembic commands ###
