"""Added quantity column

Revision ID: a7a770d51b39
Revises: 2dd9ace2403d
Create Date: 2024-09-22 21:28:03.746233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a770d51b39'
down_revision: Union[str, None] = '2dd9ace2403d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
